name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Ambiente Linux base

    steps:
      # Step 1) Clona il repository
      - uses: actions/checkout@v2

      # Step 2) Installa Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3) Installa le dipendenze
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4) Esegui i test
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings
